version: '3.2'

services:
  nginx:
    volumes:
      - ./development.nginx.conf:/etc/nginx/conf.d/site.template:ro
    environment:
      - REACT_PORT_DEV=3000
  frontend:
    environment:
      - NODE_ENV=development
  homepage:
    volumes:
      - ./apps/homepage/src:/var/www
  