version: "3.2"

services:
  nginx:
    volumes:
      - ./development.nginx.conf:/etc/nginx/conf.d/site.template:ro
    environment:
      - REACT_PORT_DEV=3000
  frontend:
    environment:
      - NODE_ENV=development
  api:
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/api/src:/usr/src/app/src
    command: sh -c "/usr/wait-for.sh mongo:27017 -- yarn run start"
  homepage:
    volumes:
      - ./apps/homepage/src:/var/www
