name: API

on:
  push:
    paths:
      - 'apps/api/**'
      - '!apps/api/*.md'
    branches:
      - master

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.8
        with:
          name: tilap/docker-js-playground/api
          username: tilap
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          workdir: apps/api
          dockerfile: Dockerfile
