name: Frontend

on:
  push:
    paths:
      - 'apps/frontend/**'
    branches:
      - master

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tilap/docker-js-playground/frontend
          username: tilap
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          workdir: apps/frontend
          dockerfile: Dockerfile
